# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib tters, .registration = TRUE
NULL

#' Expand a prepared person-time Parquet dataset into the sequential
#' target-trial layout and write the result to `output_path`.
#'
#' This is a thin FFI shim. All dtype-exact, deterministic Polars work lives in
#' the `tte_expand` core crate (which is `#![forbid(unsafe_code)]`). The binding
#' crate cannot forbid unsafe because the extendr macros emit the FFI registrar.
#' Every `tte_expand::ExpandError` is mapped to an R error condition.
#'
#' @param input_path Path to the input Parquet file.
#' @param output_path Path where the expanded Parquet is written.
#' @param id_col,period_col,treatment_col Column names in the input.
#' @param eligible_col,outcome_col Eligibility / outcome column names
#'   (`TrialEmulation` defaults are `"eligible"` / `"outcome"`).
#' @param first_period,last_period Inclusive integer bounds on `trial_period`.
#' @param estimand `"ITT"` (no artificial censoring) or `"PP"` (per-protocol,
#'   censor each trial at the first treatment deviation). Case-insensitive.
#' @return `NULL`, invisibly; the expansion is written to `output_path`. Errors
#'   in the core engine surface as R errors.
#' @examples
#' \dontrun{
#' expand_parquet(
#'   "input.parquet", "expanded.parquet",
#'   "id", "period", "treatment", "eligible", "outcome",
#'   0L, .Machine$integer.max, "ITT"
#' )
#' }
#' @export
expand_parquet <- function(input_path, output_path, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand) .Call(wrap__expand_parquet, input_path, output_path, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand)

#' Expand a person-time Parquet dataset and attach pre-computed
#' inverse-probability weights, writing the weighted frame to `output_path`.
#'
#' A thin FFI shim over `tte_expand::expand_weighted_parquet`: it expands the
#' input under `estimand`, joins the per-`(id, period)` factor table at
#' `factors_path` (`id, period, weight_factor`), and writes the six structural
#' columns plus the cumulative-product `weight`. The weight *values* come from R
#' (the `glm` fit); the engine only reproduces their deterministic accumulation.
#'
#' @param input_path Path to the input Parquet file.
#' @param factors_path Path to the per-`(id, period)` factor Parquet
#'   (`id, period, weight_factor`).
#' @param output_path Path where the weighted Parquet is written.
#' @param id_col,period_col,treatment_col Column names in the input.
#' @param eligible_col,outcome_col Eligibility / outcome column names.
#' @param first_period,last_period Inclusive integer bounds on `trial_period`.
#' @param estimand `"ITT"` or `"PP"`; selects the weight *model* upstream, but the
#'   application arithmetic (join + cumulative product) is identical for both.
#' @return `NULL`, invisibly; the weighted expansion is written to `output_path`.
#'   Errors in the core engine surface as R errors.
#' @examples
#' \dontrun{
#' expand_weighted_parquet(
#'   "input.parquet", "factors.parquet", "weighted.parquet",
#'   "id", "period", "treatment", "eligible", "outcome",
#'   0L, .Machine$integer.max, "PP"
#' )
#' }
#' @export
expand_weighted_parquet <- function(input_path, factors_path, output_path, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand) .Call(wrap__expand_weighted_parquet, input_path, factors_path, output_path, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand)

#' Fit the inverse-probability **weight factor** for a Parquet cohort in Rust and
#' write the per-`(id, period)` factor table (`id, period, weight_factor`).
#'
#' A thin FFI shim over `tte_expand::fit_weights_parquet` (the Phase-6
#' `weights-fit` surface). Unlike `expand_weighted_parquet()`, which *applies* a
#' pre-computed factor table, this *fits* the IPW models in Rust: it ports
#' `TrialEmulation`'s `data_manipulation` + `censor_func` design preparation and
#' binds a deterministic binomial-logit solver for the switching and/or IPCW
#' censoring models, then forms `wt = wt_switch * wtC`. The structural design is
#' exact; the fitted factors reproduce R `glm` within the staged ~1e-6 tolerance
#' (ADR-2), not bit-for-bit. Robust/sandwich variance and the marginal structural
#' model stay in R.
#'
#' @param input_path Path to the input Parquet cohort (long person-time).
#' @param output_path Path where the `(id, period, weight_factor)` table is written.
#' @param id_col,period_col,treatment_col Column names in the input.
#' @param eligible_col,outcome_col Eligibility / outcome column names.
#' @param first_period,last_period Inclusive integer bounds on `trial_period`.
#' @param estimand `"ITT"` or `"PP"`; per-protocol runs the artificial-censoring
#'   state machine and (with switching covariates) the switch models.
#'   Case-insensitive.
#' @param use_switch Whether to fit per-protocol switching-weight models.
#' @param switch_numerator,switch_denominator Covariate columns for the switching
#'   numerator (stabiliser) and denominator models (ignored when `use_switch` is
#'   `FALSE`).
#' @param use_censor Whether to fit inverse-probability-of-censoring (IPCW) models.
#' @param censor_col Name of the `{0,1}` censoring-indicator column; the response
#'   is `1 - censor_col` (ignored when `use_censor` is `FALSE`).
#' @param censor_numerator,censor_denominator Covariate columns for the IPCW
#'   numerator/denominator models (ignored when `use_censor` is `FALSE`).
#' @param pool_censor How the IPCW models are pooled across the previous-treatment
#'   strata: `"none"`, `"numerator"`, or `"both"`. Case-insensitive.
#' @return `NULL`, invisibly; the factor table is written to `output_path`. Errors
#'   in the core engine (including weight-fit failures) surface as R errors.
#' @examples
#' \dontrun{
#' fit_weights_parquet(
#'   "cohort.parquet", "factors.parquet",
#'   "id", "period", "treatment", "eligible", "outcome",
#'   0L, .Machine$integer.max, "PP",
#'   TRUE, c("x2"), c("x2", "x1"),
#'   FALSE, "", character(0), character(0), "none"
#' )
#' }
#' @export
fit_weights_parquet <- function(input_path, output_path, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand, use_switch, switch_numerator, switch_denominator, use_censor, censor_col, censor_numerator, censor_denominator, pool_censor) .Call(wrap__fit_weights_parquet, input_path, output_path, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand, use_switch, switch_numerator, switch_denominator, use_censor, censor_col, censor_numerator, censor_denominator, pool_censor)

#' Fit the IPW weights in Rust, expand the cohort, apply the weights, and write
#' the weighted trial frame — a raw cohort to a weighted, expanded frame in one
#' call (no pre-computed factor table).
#'
#' A thin FFI shim over `tte_expand::expand_weighted_fitted_parquet`: the fully
#' in-Rust analogue of `expand_weighted_parquet()`. It fits the switching and/or
#' IPCW models from the spec (as `fit_weights_parquet()` does), expands under
#' `estimand`, joins and accumulates the fitted factor, and writes the six
#' structural columns plus the cumulative-product `weight`. Structural columns are
#' bit-exact; `weight` matches the Oracle within the staged ~1e-6 tolerance
#' (ADR-2).
#'
#' @param input_path Path to the input Parquet cohort (long person-time).
#' @param output_path Path where the weighted, expanded Parquet is written.
#' @param id_col,period_col,treatment_col Column names in the input.
#' @param eligible_col,outcome_col Eligibility / outcome column names.
#' @param first_period,last_period Inclusive integer bounds on `trial_period`.
#' @param estimand `"ITT"` or `"PP"`. Case-insensitive.
#' @param use_switch Whether to fit per-protocol switching-weight models.
#' @param switch_numerator,switch_denominator Covariate columns for the switching
#'   numerator/denominator models (ignored when `use_switch` is `FALSE`).
#' @param use_censor Whether to fit inverse-probability-of-censoring (IPCW) models.
#' @param censor_col Name of the `{0,1}` censoring-indicator column; the response
#'   is `1 - censor_col` (ignored when `use_censor` is `FALSE`).
#' @param censor_numerator,censor_denominator Covariate columns for the IPCW
#'   numerator/denominator models (ignored when `use_censor` is `FALSE`).
#' @param pool_censor How the IPCW models are pooled across the previous-treatment
#'   strata: `"none"`, `"numerator"`, or `"both"`. Case-insensitive.
#' @return `NULL`, invisibly; the weighted expansion is written to `output_path`.
#'   Errors in the core engine (including weight-fit failures) surface as R errors.
#' @examples
#' \dontrun{
#' expand_weighted_fitted_parquet(
#'   "cohort.parquet", "weighted.parquet",
#'   "id", "period", "treatment", "eligible", "outcome",
#'   0L, .Machine$integer.max, "PP",
#'   TRUE, c("x2"), c("x2", "x1"),
#'   FALSE, "", character(0), character(0), "none"
#' )
#' }
#' @export
expand_weighted_fitted_parquet <- function(input_path, output_path, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand, use_switch, switch_numerator, switch_denominator, use_censor, censor_col, censor_numerator, censor_denominator, pool_censor) .Call(wrap__expand_weighted_fitted_parquet, input_path, output_path, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand, use_switch, switch_numerator, switch_denominator, use_censor, censor_col, censor_numerator, censor_denominator, pool_censor)

#' Expand an in-memory cohort `data.frame` into the sequential target-trial layout
#' and return the result as a `data.frame` — the frame-in/frame-out analogue of
#' `expand_parquet()`, with no intermediate Parquet.
#'
#' The cohort arrives as an R `data.frame` (a `list` of equal-length columns);
#' columns are marshalled dtype-exactly into a Polars frame (R `integer` ->
#' `Int32`, `double` -> `Float64`, `bit64::integer64` -> `Int64`), expanded by the
#' verified core, and the six structural columns are marshalled back to an R
#' `data.frame`. A 64-bit integer column (an `integer64`, e.g. a large `id`)
#' round-trips exactly via a pure-safe bit reinterpret (no precision loss).
#'
#' @param cohort An R `data.frame` of long person-time rows.
#' @param id_col,period_col,treatment_col Column names in `cohort`.
#' @param eligible_col,outcome_col Eligibility / outcome column names.
#' @param first_period,last_period Inclusive integer bounds on `trial_period`.
#' @param estimand `"ITT"` or `"PP"`. Case-insensitive.
#' @return A `data.frame` with the six structural columns (an `integer64` input
#'   column is returned as `integer64`). Errors in the core engine surface as R
#'   errors.
#' @export
expand_df <- function(cohort, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand) .Call(wrap__expand_df, cohort, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand)

#' Expand an in-memory cohort and attach pre-computed inverse-probability weights,
#' returning the weighted frame as a `data.frame` — the frame-in/frame-out
#' analogue of `expand_weighted_parquet()`.
#'
#' Both the cohort and the per-`(id, period)` factor table (`id, period,
#' weight_factor`) are passed as R `data.frame`s; the engine expands under
#' `estimand`, joins the factors, and accumulates the cumulative-product `weight`.
#' A 64-bit integer `id` (`bit64::integer64`) in either frame round-trips exactly.
#'
#' @param cohort An R `data.frame` of long person-time rows.
#' @param factors An R `data.frame` with columns `id`, `period`, `weight_factor`.
#' @param id_col,period_col,treatment_col Column names in `cohort`.
#' @param eligible_col,outcome_col Eligibility / outcome column names.
#' @param first_period,last_period Inclusive integer bounds on `trial_period`.
#' @param estimand `"ITT"` or `"PP"`. Case-insensitive.
#' @return A `data.frame` with the six structural columns plus `weight`. Errors in
#'   the core engine surface as R errors.
#' @export
expand_weighted_df <- function(cohort, factors, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand) .Call(wrap__expand_weighted_df, cohort, factors, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand)

#' Fit the inverse-probability weight factor for an in-memory cohort and return the
#' per-`(id, period)` factor table (`id, period, weight_factor`) as a `data.frame`
#' — the frame-in/frame-out analogue of `fit_weights_parquet()`.
#'
#' @param cohort An R `data.frame` of long person-time rows.
#' @param id_col,period_col,treatment_col Column names in `cohort`.
#' @param eligible_col,outcome_col Eligibility / outcome column names.
#' @param first_period,last_period Inclusive integer bounds on `trial_period`.
#' @param estimand `"ITT"` or `"PP"`. Case-insensitive.
#' @param use_switch Whether to fit per-protocol switching-weight models.
#' @param switch_numerator,switch_denominator Covariate columns for the switching
#'   numerator/denominator models (ignored when `use_switch` is `FALSE`).
#' @param use_censor Whether to fit inverse-probability-of-censoring (IPCW) models.
#' @param censor_col Name of the `{0,1}` censoring-indicator column; the response
#'   is `1 - censor_col` (ignored when `use_censor` is `FALSE`).
#' @param censor_numerator,censor_denominator Covariate columns for the IPCW
#'   numerator/denominator models (ignored when `use_censor` is `FALSE`).
#' @param pool_censor How the IPCW models are pooled across the previous-treatment
#'   strata: `"none"`, `"numerator"`, or `"both"`. Case-insensitive.
#' @return A `data.frame` with columns `id`, `period`, `weight_factor` (a 64-bit
#'   integer `id` is returned as `bit64::integer64`). Errors in the core engine
#'   (including weight-fit failures) surface as R errors.
#' @export
fit_weights_df <- function(cohort, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand, use_switch, switch_numerator, switch_denominator, use_censor, censor_col, censor_numerator, censor_denominator, pool_censor) .Call(wrap__fit_weights_df, cohort, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand, use_switch, switch_numerator, switch_denominator, use_censor, censor_col, censor_numerator, censor_denominator, pool_censor)

#' Fit the IPW weights for an in-memory cohort, expand, apply, and return the
#' weighted trial frame as a `data.frame` — a raw cohort `data.frame` straight to a
#' weighted, expanded `data.frame` in one call (no pre-computed factor table, no
#' intermediate Parquet). The frame-in/frame-out analogue of
#' `expand_weighted_fitted_parquet()`. A 64-bit integer `id` (`bit64::integer64`)
#' round-trips exactly.
#'
#' @param cohort An R `data.frame` of long person-time rows.
#' @param id_col,period_col,treatment_col Column names in `cohort`.
#' @param eligible_col,outcome_col Eligibility / outcome column names.
#' @param first_period,last_period Inclusive integer bounds on `trial_period`.
#' @param estimand `"ITT"` or `"PP"`. Case-insensitive.
#' @param use_switch Whether to fit per-protocol switching-weight models.
#' @param switch_numerator,switch_denominator Covariate columns for the switching
#'   numerator/denominator models (ignored when `use_switch` is `FALSE`).
#' @param use_censor Whether to fit inverse-probability-of-censoring (IPCW) models.
#' @param censor_col Name of the `{0,1}` censoring-indicator column; the response
#'   is `1 - censor_col` (ignored when `use_censor` is `FALSE`).
#' @param censor_numerator,censor_denominator Covariate columns for the IPCW
#'   numerator/denominator models (ignored when `use_censor` is `FALSE`).
#' @param pool_censor How the IPCW models are pooled across the previous-treatment
#'   strata: `"none"`, `"numerator"`, or `"both"`. Case-insensitive.
#' @return A `data.frame` with the six structural columns plus `weight`. Errors in
#'   the core engine (including weight-fit failures) surface as R errors.
#' @export
expand_weighted_fitted_df <- function(cohort, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand, use_switch, switch_numerator, switch_denominator, use_censor, censor_col, censor_numerator, censor_denominator, pool_censor) .Call(wrap__expand_weighted_fitted_df, cohort, id_col, period_col, treatment_col, eligible_col, outcome_col, first_period, last_period, estimand, use_switch, switch_numerator, switch_denominator, use_censor, censor_col, censor_numerator, censor_denominator, pool_censor)

# nolint end
