# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib tters, .registration = TRUE
NULL

#' Expand a prepared person-time Parquet dataset into the sequential
#' target-trial layout and write the result to `output_path`.
#'
#' @param input_path Path to the input Parquet file.
#' @param output_path Path where the expanded Parquet is written.
#' @param id_col,period_col,treatment_col Column names in the input.
#' @param first_period,last_period Inclusive integer period bounds.
#' @export
expand_parquet <- function(input_path, output_path, id_col, period_col, treatment_col, first_period, last_period) .Call(wrap__expand_parquet, input_path, output_path, id_col, period_col, treatment_col, first_period, last_period)

# nolint end

