#!/usr/bin/env bash
# shellcheck disable=SC2016  # backticks in single-quoted echoes are literal Markdown, not command substitution
# bench/run_bench.sh — R-vs-Rust runtime + peak-RSS curves for the expansion stage.
#
# Generates deterministic inputs (bench/gen.R), times the upstream R
# `data_preparation` (bench/prep.R) and the Rust engine (bench/runner) on the SAME
# parquet, captures whole-process peak RSS via `/usr/bin/time -v`, and writes a
# Markdown table to report/benchmark_data.md. Each heavy run is wrapped in a
# virtual-memory cap so the regime where R blows up dies with a clean allocation
# error instead of OOM-killing the box — while the Rust runner sails through it.
#
# Heavy + needs R + TrialEmulation + GNU /usr/bin/time. Run via `make curves`.
# Override the sweep: SIZES="2000 20000 200000 2000000" MEMCAP_KB=8000000 bash bench/run_bench.sh
set -euo pipefail
export PATH="$HOME/.cargo/bin:$PATH"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
OUT="$ROOT/report/benchmark_data.md"

# Patient counts -> ~rows (periods=14, fan-out ~3.8x). Default is a light,
# CI-friendly sweep; the R-OOM regime (>= ~5e6 input rows) is opt-in via SIZES.
read -r -a SIZES <<<"${SIZES:-700 7000 70000}"
PERIODS="${PERIODS:-14}"
MEMCAP_KB="${MEMCAP_KB:-8000000}"
SEED="${SEED:-101}"

echo ">> building Rust runner (release, one-time)..." >&2
cargo build --release --manifest-path "$ROOT/bench/runner/Cargo.toml" >&2
RUNNER="$ROOT/bench/runner/target/release/runner"

rss_mb() {
    local kb
    kb="$(grep -i 'Maximum resident set size' "$1" | grep -oE '[0-9]+' | head -1)"
    awk -v kb="${kb:-0}" 'BEGIN { printf "%.0f", kb / 1024 }'
}
elapsed() { grep -i 'Elapsed (wall clock)' "$1" | grep -oE '[0-9:.]+' | tail -1; }

{
    echo '# Benchmark data — R `data_preparation` vs Rust `tte-expand` (ITT expansion)'
    echo
    echo "Generated by \`bench/run_bench.sh\`. Cores: \`$(nproc)\`. Peak RSS is the"
    echo 'whole-process maximum from `/usr/bin/time -v`; R carries a fixed'
    echo '~210-220 MiB interpreter/arrow floor with no Rust analogue, so the RAM'
    echo 'ratio understates the engine-vs-engine gap. Memory cap per run:'
    echo "\`ulimit -v ${MEMCAP_KB}\` KiB. R wall is prep-only; Rust wall is whole-process."
    echo
    echo "| input_rows | expanded_rows | R wall_s | R maxRSS_MB | Rust wall_s | Rust maxRSS_MB | R status |"
    echo "|---:|---:|---:|---:|---:|---:|:---|"
} >"$OUT"

for n in "${SIZES[@]}"; do
    pq="$TMP/in_${n}.parquet"
    if ! Rscript "$ROOT/bench/gen.R" "$n" "$PERIODS" "$SEED" "$pq" >/dev/null 2>&1; then
        echo "gen failed n=$n" >&2
        continue
    fi
    rows="$(Rscript -e 'cat(nrow(arrow::read_parquet(commandArgs(TRUE)[1])))' "$pq" 2>/dev/null)"

    rlog="$TMP/r_${n}.log"
    rout="$TMP/r_${n}.out"
    rstatus="ok"
    (
        ulimit -v "$MEMCAP_KB"
        /usr/bin/time -v Rscript "$ROOT/bench/prep.R" "$pq"
    ) >"$rout" 2>"$rlog" || rstatus="failed"
    if grep -qiE 'cannot allocate|bad_alloc|out of memory' "$rlog" "$rout" 2>/dev/null; then
        rstatus="OOM"
    fi
    rwall="$(grep -oE 'prep_wall_s=[0-9.]+' "$rout" | cut -d= -f2 || true)"
    exprows="$(grep -oE 'expanded_rows=[0-9]+' "$rout" | cut -d= -f2 || true)"
    if [ "$rstatus" = ok ]; then rrss="$(rss_mb "$rlog")"; else rrss="NA"; fi

    ulog="$TMP/rust_${n}.log"
    (
        ulimit -v "$MEMCAP_KB"
        /usr/bin/time -v "$RUNNER" "$pq" "$TMP/out_${n}.parquet" itt
    ) >/dev/null 2>"$ulog"
    uwall="$(elapsed "$ulog")"
    urss="$(rss_mb "$ulog")"

    echo "| $rows | ${exprows:-NA} | ${rwall:-NA} | $rrss | $uwall | $urss | $rstatus |" >>"$OUT"
    echo ">> n_input=$rows  R=${rwall:-NA} s / $rrss MB ($rstatus)  Rust=$uwall / $urss MB" >&2
done

echo ">> wrote $OUT" >&2
